/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InvestigateRouteImport } from './routes/investigate'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as AnomalyRouteImport } from './routes/anomaly'
import { Route as IndexRouteImport } from './routes/index'

const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateRoute = InvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyRoute = AnomalyRouteImport.update({
  id: '/anomaly',
  path: '/anomaly',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomaly': typeof AnomalyRoute
  '/feeds': typeof FeedsRoute
  '/history': typeof HistoryRoute
  '/investigate': typeof InvestigateRoute
  '/knowledge': typeof KnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomaly': typeof AnomalyRoute
  '/feeds': typeof FeedsRoute
  '/history': typeof HistoryRoute
  '/investigate': typeof InvestigateRoute
  '/knowledge': typeof KnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomaly': typeof AnomalyRoute
  '/feeds': typeof FeedsRoute
  '/history': typeof HistoryRoute
  '/investigate': typeof InvestigateRoute
  '/knowledge': typeof KnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/anomaly' | '/feeds' | '/history' | '/investigate' | '/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anomaly' | '/feeds' | '/history' | '/investigate' | '/knowledge'
  id:
    | '__root__'
    | '/'
    | '/anomaly'
    | '/feeds'
    | '/history'
    | '/investigate'
    | '/knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomalyRoute: typeof AnomalyRoute
  FeedsRoute: typeof FeedsRoute
  HistoryRoute: typeof HistoryRoute
  InvestigateRoute: typeof InvestigateRoute
  KnowledgeRoute: typeof KnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate': {
      id: '/investigate'
      path: '/investigate'
      fullPath: '/investigate'
      preLoaderRoute: typeof InvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly': {
      id: '/anomaly'
      path: '/anomaly'
      fullPath: '/anomaly'
      preLoaderRoute: typeof AnomalyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomalyRoute: AnomalyRoute,
  FeedsRoute: FeedsRoute,
  HistoryRoute: HistoryRoute,
  InvestigateRoute: InvestigateRoute,
  KnowledgeRoute: KnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
